#BASE IMAGE
FROM python:3


#SETS WORKING DIRECTORY INSIDE DOCKER CONTAINER
#/app SPECIFY AS WORKING DIRECTORY
#ANY COMMAND LIKE RUN, COPY OR CMD WILL BE EXECUTIED RELATED TO /app
WORKDIR /app


#COPY FILES FROM HOST MACHINE TO DOCKER IMAGE ITSELF
# . SPECIFY CURRENT DIRECTORY WHERE DOCKERFILE IS LOCATED
#/app refers TO WORKING DIRECTORY WHERE ALL FILES WILL BE COPIED
COPY . /app


#DEFAULT COMMAND TO RUN WHEN CONTAINER STARTS
#COMMAND PROVIDED AS A JSON ARRAY(OR LIST) OF STRINGS
CMD ["python", "hello.py"]